In [1]:
a = (5, 6, 34, "Hello", 56.3, '@')
print((a))
print(sorted(a))

(5, 6, 34, 'Hello', 56.3, '@')


TypeError: '<' not supported between instances of 'str' and 'int'

In [2]:
b = a + (5, 3.4, "hey", '#')
print(b)

(5, 6, 34, 'Hello', 56.3, '@', 5, 3.4, 'hey', '#')


In [3]:
print(type(b))

<class 'tuple'>


# Tuples

In [4]:
a[2]

34

In [5]:
b[0:4]

(5, 6, 34, 'Hello')

In [6]:
b[::4]

(5, 56.3, 'hey')

In [14]:
c = (2,46,5,45,78,23)
print(type(c))
print(sorted(c))

<class 'tuple'>
[2, 5, 23, 45, 46, 78]


In [10]:
a = c
print(a)


(2, 4, 5, 6, 7, 23)


In [11]:
print(a)

(2, 4, 5, 6, 7, 23)


# Lists

In [16]:
l = ['a', 34, 67, 'hello',[35, 'India'], ['graphic', 'era'],72]

print(l)
print(l[4][1])

['a', 34, 67, 'hello', [35, 'India'], ['graphic', 'era'], 72]
India


In [17]:
l1 = ['asdf', 56, 20]
print(l + l1)

['a', 34, 67, 'hello', [35, 'India'], ['graphic', 'era'], 72, 'asdf', 56, 20]


#### List are mutable

In [19]:
l1[0] = 96
print(l1)

[96, 56, 20]


##### Extand the list

In [21]:
l1.extend(['hindi', 'english', 70])
print(l1)

[96, 56, 20, 'hindi', 'english', 70, 'hindi', 'english', 70]


#### apend

In [42]:
l3 = [69, 'hi']
print(l3)
print(l1.append(l3)) #pata nahi kya hua

[69, 'hi']
None


In [44]:
l4 = ['asdf', 29, 56]
l4.append(['hi', 67, 69])
print(l4)

['asdf', 29, 56, ['hi', 67, 69]]


#### converting a 'string' to a 'list'

In [34]:
str_list = "Hello Graphic Era".split()
print(str_list)
print(type(str_list))

['Hello', 'Graphic', 'Era']
<class 'list'>


In [54]:
str2 = "amritesh, pashupati, 46, nath"
print(str2.split(","))
print(type(str2))

['amritesh', ' pashupati', ' 46', ' nath']
<class 'str'>


In [33]:
print(type(str2))

<class 'tuple'>


#### clone a list

In [37]:
l2 = l1[:]
print(l2)
l1[0] = 'hi'
print(l1)
print(l2)

[96, 56, 20, 'hindi', 'english', 70, 'hindi', 'english', 70]
['hi', 56, 20, 'hindi', 'english', 70, 'hindi', 'english', 70]
[96, 56, 20, 'hindi', 'english', 70, 'hindi', 'english', 70]


# Sets and Dictionaries

In [59]:
s = {1, 56, 84, 119, 1, 'hello', 4.9}
print(s)
print(type(s))

{1, 4.9, 84, 'hello', 119, 56}
<class 'set'>


#### convert list to a set

In [56]:
l = ['hello', 1, 5, 1, 3.7, 'hi']
s1 = set(l)
print(s1)
print(type(l))
print(type(s1))

{1, 3.7, 5, 'hi', 'hello'}
<class 'list'>
<class 'set'>


### operations on set

###### addition

In [57]:
s.add("graphic era")
print(s)

{1, 4.9, 84, 'hello', 'graphic era', 119, 56}


##### remove

In [60]:
s.remove(84)
print(s)

{1, 4.9, 'hello', 119, 56}


##### Searching

In [61]:
1 in s

True

##### intersection 

In [62]:
s1 = {1, 5, 87, 34}
print(s & s1)

{1}


##### Union

In [63]:
print(s.union(s1) )

{1, 34, 4.9, 5, 'hello', 87, 119, 56}


##### subset

In [67]:
s2 = {1, 5}
s2.issubset(s1)


True

In [87]:
dic = {"apple": 203,
      "oranges": 564,
      "banana": 241}

print(dic)
print(type(dic))

{'apple': 203, 'oranges': 564, 'banana': 241}
<class 'dict'>


##### searching

In [88]:
dic['oranges']

564

#### delete

In [89]:
del dic["banana"]
print(dic)

{'apple': 203, 'oranges': 564}


In [75]:
dic.keys()

dict_keys(['apple', 'oranges'])

In [76]:
dic.values()

dict_values([203, 564])

In [90]:
dic['pumpkin'] = 5687
print(dic)

{'apple': 203, 'oranges': 564, 'pumpkin': 5687}


# Comparisons, Branching and Loops

In [93]:
x = 4

x == 4


True

In [94]:
x == 7

False

In [95]:
#Branching

study = 6

if (study < 6):
    print("you have to study more")
elif (study == 6):
    print("if you want to study you can do it")
else:
    print("do what you want")

if you want to study you can do it


In [96]:
# Loops

shapes = ['triangle', 'circle', 'square', 'rectangle']

for i in range(0,4):
    shapes[i] = 'line'
print(shapes)

['line', 'line', 'line', 'line']


In [97]:
shapes1 = ['triangle', 'circle', 'square', 'rectangle']

for shapes in shapes:
    shapes = 'line'
print(shapes)

line


# Numpy Basics

In [98]:
import numpy as np

In [99]:
a = np.array([2,45,62,73,96])

In [102]:
print(a)

[ 2 45 62 73 96]


In [103]:
type(a)

numpy.ndarray

In [104]:
a.dtype #its says that datatype is of int type and of 64 bits

dtype('int64')

In [106]:
b = np.array([2,5,11,-5,7,36], np.int32)

b.dtype

dtype('int32')

In [107]:
a.size

5

In [108]:
a.shape # is a tupe of integers indecatiog the size of the array in its dimensions

(5,)

In [110]:
a.ndim

1

In [111]:
a[2]

62

In [112]:
a[1:4]

array([45, 62, 73])

In [113]:
a[0] = -12
print(a)

[-12  45  62  73  96]


In [115]:
a[1:3] = 2,50
print(a)

[-12   2  50  73  96]


## numpy operation frequently used in data science

##### Vector addition/ subtraction

In [121]:
a = np.array([2,4,6])
b = np.array([5,9,8])

c = a+b
d = a-b
e = a*2
print(c)
print(d)
print(e)
print(type(c))

[ 7 13 14]
[-3 -5 -2]
[ 4  8 12]
<class 'numpy.ndarray'>


##### Hadamard product (element wise multiplication)

In [122]:
z = a*b
print(z)

[10 36 48]


##### dot product

In [124]:
x = np.dot(a,b)
print(x)

94


### Universal functions

In [127]:
print(b.mean())
print(b.max())

7.333333333333333
9


#### Line space:- returns evenly space number over a specified interval

In [ ]:
# u = np.linspace(5, 55, num = 3 ) # num = 3, tells that give me 3 sampales between 5 & 55 which will be evenly spaced.
print(u)

# 2-D Numpy arrays

In [138]:
a = [[2,5,8,6],[3,6,1,7],[6,4,0,1]]
b = np.array(a)
print(b)

[[2 5 8 6]
 [3 6 1 7]
 [6 4 0 1]]


In [133]:
b.ndim # shows the dimensions of the array or rank of the array
# note:- here the rank refers to the dimension of the matrix not that rank which are in maths

2

In [139]:
b.shape

(3, 4)

In [140]:
b.size

12

In [141]:
b[0][1]

5

In [142]:
b[0,0:2]

array([2, 5])

In [143]:
b[0:2, 3]

array([6, 7])

In [154]:
x = np.array([[3,6,9],[5,8,2], [7,4,9]])
y = np.array([[2,5,8], [ 4,3,0], [8,2,4]])

print(x+y,'\n')
print(x-y,'\n')
print(x*y)

[[ 5 11 17]
 [ 9 11  2]
 [15  6 13]] 

[[ 1  1  1]
 [ 1  5  2]
 [-1  2  5]] 

[[ 6 30 72]
 [20 24  0]
 [56  8 36]]


In [155]:
z = np.dot(x,y) #matrix multiplication
print(z)

[[102  51  60]
 [ 58  53  48]
 [102  65  92]]


# Pandas

In [1]:
import pandas as pd

In [22]:
df = pd.read_csv('Data.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [23]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

###### Create new data from existing data

In [24]:
df1 = df['Age']
print(df1)
print(type(df1))

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64
<class 'pandas.core.series.Series'>


In [27]:
df1 = df[['Age', 'Salary', 'Country']]
df1

Age   Salary  Country
0  44.0  72000.0   France
1  27.0  48000.0    Spain
2  30.0  54000.0  Germany
3  38.0  61000.0    Spain
4  40.0      NaN  Germany
5  35.0  58000.0   France
6   NaN  52000.0    Spain
7  48.0  79000.0   France
8  50.0  83000.0  Germany
9  37.0  67000.0   France

In [16]:
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [17]:
dfnew = df[df['Salary']>= 70000]

In [18]:
dfnew

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No

##### save it to csv file

In [28]:
dfnew.to_csv('newdata.csv')

In [29]:
df = pd.read_csv('Sales_Data.csv')

In [30]:
df.head()

Country Region Sales Person   Date of Purchase   Total  Quantity
0      India  North         John  8/28/2016 0:00:00  100000       567
1         US  North         Bill  4/27/2018 0:00:00  120000      3000
2         UK  North       Thomas  8/21/2011 0:00:00  140000       345
3  Australia   East         John  2/11/2014 0:00:00  160000      1000
4     Africa   East         Bill  7/30/2011 0:00:00  180000       123

##### adding a new column

In [32]:
Tokens = [10]*10 + [40]*10
df['Tokens'] = Tokens
df

Country Region Sales Person    Date of Purchase     Total  Quantity  \
0       India  North         John   8/28/2016 0:00:00    100000       567   
1          US  North         Bill   4/27/2018 0:00:00    120000      3000   
2          UK  North       Thomas   8/21/2011 0:00:00    140000       345   
3   Australia   East         John   2/11/2014 0:00:00    160000      1000   
4      Africa   East         Bill   7/30/2011 0:00:00    180000       123   
5   Singapore   East       Thomas   7/20/2014 0:00:00    200000      1000   
6     Mylasia   West         John   5/17/2015 0:00:00   1000000      7890   
7       India   West         Bill    3/8/2015 0:00:00    240000       200   
8          US   West       Thomas  11/29/2012 0:00:00  26000000      1000   
9          UK  North         John   2/12/2015 0:00:00    100000      1000   
10  Australia  North         Bill    6/5/2016 0:00:00    120000       567   
11     Africa  North       Thomas   5/21/2014 0:00:00    140000      1000   
12  Singapore   East         John  12/24/2010 0:00:00    160000       892   
13    Mylasia   East         Bill   12/3/2018 0:00:00    180000       444   
14      India   East       Thomas   9/30/2014 0:00:00    200000        90   
15         US   West         John   2/10/2018 0:00:00    220000        90   
16         UK   West         Bill   11/4/2010 0:00:00    240000        90   
17  Australia   West       Thomas   8/30/2014 0:00:00    260000        90   
18     Africa  North         John   12/2/2015 0:00:00    140000        85   
19  Singapore  North         Bill   4/22/2010 0:00:00    150000        85   

    Tokens  
0       10  
1       10  
2       10  
3       10  
4       10  
5       10  
6       10  
7       10  
8       10  
9       10  
10      40  
11      40  
12      40  
13      40  
14      40  
15      40  
16      40  
17      40  
18      40  
19      40

##### adding a Row 

In [33]:
new_row = ['Canada', 'Wast', 'Joe', '8/30/2014 0:00:00', '48740', '59', '69']

In [34]:
pd.DataFrame(new_row)  #The record is converted into data frame
                       #This row has to represent as list

0
0             Canada
1               Wast
2                Joe
3  8/30/2014 0:00:00
4              48740
5                 59
6                 69

In [35]:
new_df = pd.DataFrame([new_row])
# Nowthis record can be inserted into the Data Frame but these values are need
# to correctly map to the appropate column

In [36]:
new_df = pd.DataFrame([new_row], columns= df.columns.values)

In [37]:
df.append(new_df)

Country Region Sales Person    Date of Purchase     Total Quantity  \
0       India  North         John   8/28/2016 0:00:00    100000      567   
1          US  North         Bill   4/27/2018 0:00:00    120000     3000   
2          UK  North       Thomas   8/21/2011 0:00:00    140000      345   
3   Australia   East         John   2/11/2014 0:00:00    160000     1000   
4      Africa   East         Bill   7/30/2011 0:00:00    180000      123   
5   Singapore   East       Thomas   7/20/2014 0:00:00    200000     1000   
6     Mylasia   West         John   5/17/2015 0:00:00   1000000     7890   
7       India   West         Bill    3/8/2015 0:00:00    240000      200   
8          US   West       Thomas  11/29/2012 0:00:00  26000000     1000   
9          UK  North         John   2/12/2015 0:00:00    100000     1000   
10  Australia  North         Bill    6/5/2016 0:00:00    120000      567   
11     Africa  North       Thomas   5/21/2014 0:00:00    140000     1000   
12  Singapore   East         John  12/24/2010 0:00:00    160000      892   
13    Mylasia   East         Bill   12/3/2018 0:00:00    180000      444   
14      India   East       Thomas   9/30/2014 0:00:00    200000       90   
15         US   West         John   2/10/2018 0:00:00    220000       90   
16         UK   West         Bill   11/4/2010 0:00:00    240000       90   
17  Australia   West       Thomas   8/30/2014 0:00:00    260000       90   
18     Africa  North         John   12/2/2015 0:00:00    140000       85   
19  Singapore  North         Bill   4/22/2010 0:00:00    150000       85   
0      Canada   Wast          Joe   8/30/2014 0:00:00     48740       59   

   Tokens  
0      10  
1      10  
2      10  
3      10  
4      10  
5      10  
6      10  
7      10  
8      10  
9      10  
10     40  
11     40  
12     40  
13     40  
14     40  
15     40  
16     40  
17     40  
18     40  
19     40  
0      69

# Pandas III

In [5]:
import pandas as pd
df = pd.read_csv('Sales_Data.csv')

In [6]:
df.head()

Country Region Sales Person   Date of Purchase   Total  Quantity
0      India  North         John  8/28/2016 0:00:00  100000       567
1         US  North         Bill  4/27/2018 0:00:00  120000      3000
2         UK  North       Thomas  8/21/2011 0:00:00  140000       345
3  Australia   East         John  2/11/2014 0:00:00  160000      1000
4     Africa   East         Bill  7/30/2011 0:00:00  180000       123

In [7]:
#information about data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Country           20 non-null     object
 1   Region            20 non-null     object
 2   Sales Person      20 non-null     object
 3   Date of Purchase  20 non-null     object
 4   Total             20 non-null     int64 
 5   Quantity          20 non-null     int64 
dtypes: int64(2), object(4)
memory usage: 1.1+ KB


#### How to make column as an index

In [8]:
# first make a new column with the help of module'random'
# and from the module'random' use function 'sample'

import random

In [9]:
l = random.sample(range(1000,10050),20)

In [11]:
print(l)

[2773, 7444, 3159, 5393, 5482, 3052, 1422, 5300, 9483, 1516, 2212, 4665, 9471, 2345, 8407, 6568, 8562, 4826, 7386, 4229]


In [16]:
# now insert this unique random no. to the data frame
df['Bill No.'] = l
df.head()

Country Region Sales Person   Date of Purchase   Total  Quantity  \
Bill No.                                                                       
2773          India  North         John  8/28/2016 0:00:00  100000       567   
7444             US  North         Bill  4/27/2018 0:00:00  120000      3000   
3159             UK  North       Thomas  8/21/2011 0:00:00  140000       345   
5393      Australia   East         John  2/11/2014 0:00:00  160000      1000   
5482         Africa   East         Bill  7/30/2011 0:00:00  180000       123   

          Bill No.  
Bill No.            
2773          2773  
7444          7444  
3159          3159  
5393          5393  
5482          5482

In [17]:
# make Bill no. as index
df.set_index('Bill No.', inplace= True)
# Inpace = True:- this will do change in main data frame
df.head()

Country Region Sales Person   Date of Purchase   Total  Quantity
Bill No.                                                                    
2773          India  North         John  8/28/2016 0:00:00  100000       567
7444             US  North         Bill  4/27/2018 0:00:00  120000      3000
3159             UK  North       Thomas  8/21/2011 0:00:00  140000       345
5393      Australia   East         John  2/11/2014 0:00:00  160000      1000
5482         Africa   East         Bill  7/30/2011 0:00:00  180000       123

In [18]:
# If we want indexin sorted form

df.sort_index()

Country Region Sales Person    Date of Purchase     Total  \
Bill No.                                                                
1422        Mylasia   West         John   5/17/2015 0:00:00   1000000   
1516             UK  North         John   2/12/2015 0:00:00    100000   
2212      Australia  North         Bill    6/5/2016 0:00:00    120000   
2345        Mylasia   East         Bill   12/3/2018 0:00:00    180000   
2773          India  North         John   8/28/2016 0:00:00    100000   
3052      Singapore   East       Thomas   7/20/2014 0:00:00    200000   
3159             UK  North       Thomas   8/21/2011 0:00:00    140000   
4229      Singapore  North         Bill   4/22/2010 0:00:00    150000   
4665         Africa  North       Thomas   5/21/2014 0:00:00    140000   
4826      Australia   West       Thomas   8/30/2014 0:00:00    260000   
5300          India   West         Bill    3/8/2015 0:00:00    240000   
5393      Australia   East         John   2/11/2014 0:00:00    160000   
5482         Africa   East         Bill   7/30/2011 0:00:00    180000   
6568             US   West         John   2/10/2018 0:00:00    220000   
7386         Africa  North         John   12/2/2015 0:00:00    140000   
7444             US  North         Bill   4/27/2018 0:00:00    120000   
8407          India   East       Thomas   9/30/2014 0:00:00    200000   
8562             UK   West         Bill   11/4/2010 0:00:00    240000   
9471      Singapore   East         John  12/24/2010 0:00:00    160000   
9483             US   West       Thomas  11/29/2012 0:00:00  26000000   

          Quantity  
Bill No.            
1422          7890  
1516          1000  
2212           567  
2345           444  
2773           567  
3052          1000  
3159           345  
4229            85  
4665          1000  
4826            90  
5300           200  
5393          1000  
5482           123  
6568            90  
7386            85  
7444          3000  
8407            90  
8562            90  
9471           892  
9483          1000

In [20]:
df.sort_index(ascending= False).head()

Country Region Sales Person    Date of Purchase     Total  \
Bill No.                                                                
9483             US   West       Thomas  11/29/2012 0:00:00  26000000   
9471      Singapore   East         John  12/24/2010 0:00:00    160000   
8562             UK   West         Bill   11/4/2010 0:00:00    240000   
8407          India   East       Thomas   9/30/2014 0:00:00    200000   
7444             US  North         Bill   4/27/2018 0:00:00    120000   

          Quantity  
Bill No.            
9483          1000  
9471           892  
8562            90  
8407            90  
7444          3000

In [21]:
# if we want to sort according to other value not index

df.sort_values('Country')

Country Region Sales Person    Date of Purchase     Total  \
Bill No.                                                                
5482         Africa   East         Bill   7/30/2011 0:00:00    180000   
7386         Africa  North         John   12/2/2015 0:00:00    140000   
4665         Africa  North       Thomas   5/21/2014 0:00:00    140000   
4826      Australia   West       Thomas   8/30/2014 0:00:00    260000   
5393      Australia   East         John   2/11/2014 0:00:00    160000   
2212      Australia  North         Bill    6/5/2016 0:00:00    120000   
2773          India  North         John   8/28/2016 0:00:00    100000   
8407          India   East       Thomas   9/30/2014 0:00:00    200000   
5300          India   West         Bill    3/8/2015 0:00:00    240000   
2345        Mylasia   East         Bill   12/3/2018 0:00:00    180000   
1422        Mylasia   West         John   5/17/2015 0:00:00   1000000   
9471      Singapore   East         John  12/24/2010 0:00:00    160000   
4229      Singapore  North         Bill   4/22/2010 0:00:00    150000   
3052      Singapore   East       Thomas   7/20/2014 0:00:00    200000   
3159             UK  North       Thomas   8/21/2011 0:00:00    140000   
8562             UK   West         Bill   11/4/2010 0:00:00    240000   
1516             UK  North         John   2/12/2015 0:00:00    100000   
6568             US   West         John   2/10/2018 0:00:00    220000   
7444             US  North         Bill   4/27/2018 0:00:00    120000   
9483             US   West       Thomas  11/29/2012 0:00:00  26000000   

          Quantity  
Bill No.            
5482           123  
7386            85  
4665          1000  
4826            90  
5393          1000  
2212           567  
2773           567  
8407            90  
5300           200  
2345           444  
1422          7890  
9471           892  
4229            85  
3052          1000  
3159           345  
8562            90  
1516          1000  
6568            90  
7444          3000  
9483          1000